### ISSUE TITLE
tag and contributor names are case sensitive

### ISSUE THREAD

**Issue by wrick17** [wrick17/spendy-api#19]
As of now the `tag` name and `contributor` name are case sensitive. as in `name` =/= `Name`.

So if a `contributor` or `tag` has an entry called `name` and we add one more entry called `Name` it is accepted. 

So we have two options:
- We make `tag` name and `contributor` name case sensitive and show them as it is, ie, 

```
    name =/= Name
```
- We make `tag` name and `contributor` name non - case sensitive and control their case sensitivity in CSS, in which case all the `names` will be same in both cases, ie, 

```
    nAme = Name
```

**Comment by UtsavDawn** [comment]
Now every tag and contributor name will be stored in case-insensitive format. Solved in PR #20
